## Lab: CI/CD with blue green deployment

In this lab we are going to deploy 2 custom made applications on OpenShift:

- demo-color-api - serves as a public facing app
- demo-color-backend - serves data to demo-color-api

We will show you how to deploy these application on OpenShift, how to use Jenkins
to achieve continuous integration and continuous delivery of these application
on OpenShift.

Finally we will show you how to achieve deployment stability via Blue/Green
deployment. Blue/Green deployment is a technique to address the challenges
of continuous deployment like a minimizing downtime during new version enrollment.
It also enables you to quickly rollback any changes as it is based about the idea
of having two identical environment called "blue" and "green" and switching
between them

### Exercise: Deploy demo-color-backend

*Login to oc cluster*

Go to `https://<OC-CLUSTER-ADDRESS>/console/command-line` and copy `oc login ...` snippet.

--------
$ oc login ...
--------

*Create project*

--------
$ oc new-project <NAME>
--------


We will deploy demo-color-backend application on our OpenShift cluster. To be able
to do it, we will first app repository:

[source]
--------
$ git clone https://github.com/prgcont/demo-color-backend
--------

As we mentioned above, we will need to deploy this service to two environments.
We need to deploy DeploymentConfig, service and a Route.

To deploy a blue one, run:
[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-backend/master/template.app.yaml COLOR=blue | oc apply -f -
--------

To deploy a green one, run:
[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-backend/master/template.app.yaml COLOR=green | oc apply -f -
--------

Finally we need to deploy our pipeline, which is responsible for deploying our
application and switching master route. To do it, run:

[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-backend/master/template.pipeline.yaml | oc apply -f -
--------

You can see whats happening in the cluster by invoking:
[source]
--------
$ oc get all
--------

Alternatively, you can use OpenShift web console to examine deployed resources.

*Tasks:*

- Use cat and compare template definition with objects defined in corresponding OpenShift Projects
- Login to Jenkins a look at the defined pipeline


### Exercise: demo-color-api

This service serves as our public facing application we will access during workshop. It uses
demo-color-backend via its master route.

We begin with cloning demo-control-api repository

[source]
--------
$ git clone https://github.com/prgcont/demo-color-api
--------

Again, we will deploy blue and green apps, starting with blue:
[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-api/master/template.app.yaml COLOR=blue | oc apply -f -
--------

And a green one:
[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-api/master/template.app.yaml COLOR=green | oc apply -f -
--------

These will also deploy a master route which will allow us switch between deployments

We also need to configure our application. There is a URL expected in configmap.yaml file. The value should match the master route host value from https://github.com/prgcont/demo-color-backend. The value needs to be in a form ``http://$HOST:$PORT``. You can obviously omit $PORT if it equals to 80.

After you update the value there, you'll need to upload the config to OpenShift

[source]
--------
$ oc apply -f https://raw.githubusercontent.com/prgcont/demo-color-api/master/configmap.yaml
--------

At the end, we will again deploy the pipeline.

[source]
--------
$ oc process -f https://raw.githubusercontent.com/prgcont/demo-color-api/master/template.pipeline.yaml | oc apply -f -
--------

You can see whats happening in the cluster by invoking:
[source]
--------
$ oc get all
--------

Alternatively, you can use OpenShift web console to examine deployed resources.


*Tasks:*

- Access demo-color-api applications via blue and green route.
- Determine which deployment (blue or green is accessible via master route)


## Exercise: Blue green deployment

Login to do OpenShift console and via `Builds -> Pipelines` and stat demo-color-backend pipeline
via `Start Pipeline`.

Once the build is finished, you should to your new deployment.

*Tasks:*

- Do multiple demo-color-backend and demo-color-api deployment switches
- Explain how blue and green deployment of demo-color-backend changed demo-color-api
- Try to not proceed your deployment, what happens?
- Try to patch master route manually
